[package]
name = "AuroraRust"
version = "0.1.0"
authors = ["teamaffixmb-pablo <66919907+teamaffixmb-pablo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
